#!/bin/bash
set -euo pipefail

rm -rf /workspace/exercise /workspace/solution
cp -r /workspace/exercises/4_local_activities/practice /workspace/exercise
cp -r /workspace/exercises/4_local_activities/solution /workspace/solution

echo "Exercise 4 ready."
echo "Files are in /workspace/exercise/"
